# Generated by Django 5.2 on 2025-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='style',
            field=models.CharField(default='friendly', max_length=100),
        ),
    ]
